version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
  open-pull-requests-limit: 10
  target-branch: dependa
  reviewers:
  - Alexandrshy
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@semantic-release/npm"
    versions:
    - 7.0.10
    - 7.1.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
  - dependency-name: "@babel/plugin-proposal-decorators"
    versions:
    - 7.12.12
    - 7.12.13
    - 7.13.5
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
  commit-message:
    prefix: fix
